name: cuvalley2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - openpyxl
  - pandas
  - numpy
  - fastapi
  - httpx
  - uvicorn
  - python-multipart
  - pip
  - pip:
    - prospector
